### ISSUE TITLE
Test example "afd_private_link_service_to_LB" in module "avm-res-cdn-profile" fail

### ISSUE THREAD

**Issue by zhangjiale-64** [Azure/terraform-azurerm-avm-res-cdn-profile#37]
**Describe the issue:**

Test the example [`avm-res-cdn-profile_example_afd_private_link_service_to_LB`](https://registry.terraform.io/modules/Azure/avm-res-cdn-profile/azurerm/latest/examples/afd_private_link_service_to_LB), there is an error occurs when we open the created resource in azure portal. The subnet/frontend subnet creation fails, because it attempt to enable network policy for the Private Link service on the subnet. 
The error as follow：

![image](https://github.com/Azure/terraform-azurerm-avm-res-cdn-profile/assets/141405558/43599552-c124-4c0c-9747-e2dab4f78803)

**Repro Steps:**

1. Clone a terraform template, such as `todo-python-mongo-terraform`.
2. Replace the content of the sample [afd_private_link_service_to_LB](https://registry.terraform.io/modules/Azure/avm-res-cdn-profile/azurerm/latest/examples/afd_private_link_service_to_LB) into the main.tf file of terraform, and comment out the content of the `output.tf` file in terraform.
3. Login in with command: `az login`, `azd auth login` .
4. Run `azd provision`.
5. Open the created resources in azure portal.

**Module Version** : 0.1.0

**Expected behavior:**
All resources can be created successfully, there is no error in azure portal.

@didayal-msft , @Poven795909 and @jongio for notification.

**Comment by didayal-msft** [comment]
Thanks for submitting the issue @zhangjiale-64 
I wanted to confirm if the below setting or any other setting has been changed in the configuration? 

![image](https://github.com/Azure/terraform-azurerm-avm-res-cdn-profile/assets/81250915/75801c4a-c1c1-4d28-b1aa-e597105e9de9)

Please feel free to connect internally

**Comment by zhangjiale-64** [comment]
> Thanks for submitting the issue @zhangjiale-64 I wanted to confirm if the below setting or any other setting has been changed in the configuration?
> 
> ![image](https://private-user-images.githubusercontent.com/81250915/341468922-75801c4a-c1c1-4d28-b1aa-e597105e9de9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTM2NDYsIm5iZiI6MTcxODk1MzM0NiwicGF0aCI6Ii84MTI1MDkxNS8zNDE0Njg5MjItNzU4MDFjNGEtYzFjMS00ZDI4LWIxYWEtZTU5NzEwNWU5ZGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA3MDIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxODlkZGM1NTExOTNjNjNjMTc0YTI4ZDIxY2M3NDI2N2ZjYWM1NDZjZDkzMzA2MjY2ZDNkYjU3NDkyMWE4MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5__FTuU78ooeV-Tz0FQPuWNMpbsQZP3OFIPVcrJC0Qk)
> 
> Please feel free to connect internally

The settings in the configuration have not changed.

**Comment by Poven795909** [comment]
@zhangjiale-64 I will test at my end and will reach out to you offline for sync on this.

**Comment by Poven795909** [comment]
From the screenshot shared, it looks like the error is while applying NSG rules to the subnet. The example code doesnt apply any NSG rules. Looks like the issue due to some organizational policies applied at the subscription level automatically when new subnets are created. The issue is not reproducible at our end with the default configuration.

**Comment by v-xuto** [comment]
> From the screenshot shared, it looks like the error is while applying NSG rules to the subnet. The example code doesnt apply any NSG rules. Looks like the issue due to some organizational policies applied at the subscription level automatically when new subnets are created. The issue is not reproducible at our end with the default configuration.

@jongio Any ideas?

**Comment by jongio** [comment]
I'm asking...

**Comment by Poven795909** [comment]
@jongio  greetings! were you able to identify the policy impacting the deployment ? We discussed with the AVM core team and have agreed that this issue is related to a subscription policy and not related to the module. If this policy is related to the Azure landing zone , do let us know and we will reach out to the ALZ team for review.

**Comment by jongio** [comment]
I did ask around, but we aren't able to determine the cause of this based on the data we have.  Yes, any help would be appreciated.

**Comment by Poven795909** [comment]
Opened an internal group chat to discuss further. We need access to the  Azure SDK Developer Playground subscription to review the policies.

**Comment by Poven795909** [comment]
As discussed internally since the failure the is due to NSGs getting deployed through a DINE policy, this is not a module issue. As per terraforms official article for azurerm_subnet , NSGs are not supported for Private link services https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet . Please work internally to get necessary exceptions to the resource groups on these policies.
